const books=[
{key:'revenue',title:'From Req to Revenue',cats:['recruiting','revenue'],cover:'https://static.wixstatic.com/media/ccfe83_3be052b4efe44b18859835838ebe435a~mv2.png/v1/fill/w_980,h_1470,al_c,q_90,enc_auto/Req%20to%20Revenue%20cover.png',desc:'Turn every open requisition into predictable, repeatable income and build stronger client ownership.',url:'https://www.amazon.com/s?k=From+Req+to+Revenue+Jay+Tyler'},
{key:'ai',title:'AI Powered Technical Recruiting',cats:['recruiting','ai'],cover:'https://static.wixstatic.com/media/ccfe83_390619cfcfcf43ae8cfba8f3dcdede33~mv2.jpg/v1/fill/w_980,h_1470,al_c,q_85,enc_auto/AI%20Powered%20Technical%20Recruiting%20-%20Cover.jpg',desc:'Use AI to source smarter, screen faster and combine automation with human judgment.',url:'https://www.amazon.com/s?k=AI+Powered+Technical+Recruiting+Jay+Tyler'},
{key:'interview',title:'Interviewing in the Age of AI',cats:['recruiting','ai'],cover:'https://static.wixstatic.com/media/ccfe83_cdbfe447f75a49678e8fc55ec37b3b6c~mv2.jpg/v1/fill/w_980,h_1470,al_c,q_85,enc_auto/Interviewing%20in%20the%20Age%20of%20AI.jpg',desc:'Adapt interviewing for a world of automation, data and AI-assisted candidates.',url:'https://www.amazon.com/s?k=Interviewing+in+the+Age+of+AI+Jay+Tyler'},
{key:'bdai',title:'AI-Powered Business Development for Technical Staffing',cats:['sales','ai'],cover:'https://static.wixstatic.com/media/ccfe83_d2e7400b537f493eb60243e93f832a6a~mv2.jpg/v1/fill/w_980,h_1470,al_c,q_85,enc_auto/AI%20Powered%20Business%20Development%20-%20Cover.jpg',desc:'Use automation, buying signals and personalization to build a predictable technical staffing pipeline.',url:'https://www.amazon.com/s?k=AI-Powered+Business+Development+for+Technical+Staffing+Jay+Tyler'},
{key:'salesai',title:'The AI Recruiting Sales Machine',cats:['sales','ai','revenue'],cover:'https://static.wixstatic.com/media/ccfe83_4e35a6ff32e541379d2df5f007ef8708~mv2.jpg/v1/fill/w_980,h_1470,al_c,q_85,enc_auto/The%20AI%20Recruiting%20Sales%20Machine%20-%20Book%20Cover.jpg',desc:'Combine AI with proven recruiting strategy to create a scalable sales and prospecting engine.',url:'https://www.amazon.com/s?k=The+AI+Recruiting+Sales+Machine+Jay+Tyler'},
{key:'engine',title:'The AI Revenue Engine for Recruiting Firms',cats:['sales','ai','revenue'],cover:'https://static.wixstatic.com/media/ccfe83_30db17dd885546fea96d541a76961d27~mv2.jpg/v1/fill/w_980,h_1470,al_c,q_85,enc_auto/The%20AI%20Revenue%20Engine%20for%20Recruiting%20Firms%20-%20Cover_upscayl_5x_upscayl-standard-4x.jpg',desc:'Integrate AI across sales, delivery, expansion and retention to engineer predictable growth.',url:'https://www.amazon.com/s?k=The+AI+Revenue+Engine+for+Recruiting+Firms+Jay+Tyler'},
{key:'margin',title:'High Margin Recruiting',cats:['sales','revenue'],cover:'https://static.wixstatic.com/media/ccfe83_893475a1e50d46e49fcbee00cb35e4fa~mv2.jpg/v1/fill/w_980,h_1470,al_c,q_85,enc_auto/High%20Margin%20Recruiting%20Cover.jpg',desc:'Increase fees, improve deal structure and protect your value in every search.',url:'https://www.amazon.com/s?k=High+Margin+Recruiting+Jay+Tyler'},
{key:'bd',title:'Business Development for Recruiters (Who Hate Selling)',cats:['sales'],cover:'https://static.wixstatic.com/media/ccfe83_0a495159056d491fb56790ee01c8f5cc~mv2.jpg/v1/crop/x_60,y_35,w_964,h_1501/fill/w_944,h_1470,al_c,q_85,enc_auto/Business%20Development%20for%20Recruiter%20Cover.jpg',desc:'A practical system for winning clients, handling objections and turning cold outreach into relationships.',url:'https://www.amazon.com/s?k=Business+Development+for+Recruiters+Who+Hate+Selling+Jay+Tyler'}];
const grid=document.querySelector('#bookGrid');
function render(filter='all'){grid.innerHTML=books.filter(b=>filter==='all'||b.cats.includes(filter)).map(b=>`<article class="book-card"><div class="book-cover-wrap"><img class="book-cover" src="${b.cover}" alt="${b.title} book cover"></div><div class="book-info"><div class="book-tags">${b.cats.join(' • ')}</div><h3>${b.title}</h3><p>${b.desc}</p><a class="book-link" target="_blank" rel="noopener" href="${b.url}">View on Amazon ↗</a></div></article>`).join('')}
render();
document.querySelectorAll('.filter').forEach(x=>x.onclick=()=>{document.querySelectorAll('.filter').forEach(y=>y.classList.remove('active'));x.classList.add('active');render(x.dataset.filter)});
const recs={bd:books[7],ai:books[4],margin:books[6],revenue:books[0]};
document.querySelectorAll('.goal').forEach(x=>x.onclick=()=>{document.querySelectorAll('.goal').forEach(y=>y.classList.remove('active'));x.classList.add('active');const b=recs[x.dataset.book];recTitle.textContent=b.title;recText.textContent=b.desc;recLink.href=b.url});
document.querySelector('.menu-toggle').onclick=()=>document.querySelector('.nav').classList.toggle('open');
const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));

const leadForm=document.querySelector('#leadForm');if(leadForm){leadForm.addEventListener('submit',e=>{e.preventDefault();alert('This is the preview form. We will connect it to your email list before launch.');});}
